version: '3.4'

services:
  scrapte84kmv:
    image: scrapte84kmv
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        - NODE_ENV=${NODE_ENV}
        - DB_HOST=${DB_HOST}
        - DB_NAME=${DB_NAME}
    restart: always
    depends_on:
      - db
  db:
      image: mongo
      volumes:
        - .docker/data/db:/data/db
      restart: always