version: '3.4'

services:
  scrapte84kmv:

      context: .
      dockerfile: ./Dockerfile
    environment:
        - NODE_ENV=${NODE_ENV}
        - DB_HOST=${DB_HOST}
        - DB_NAME=${DB_NAME}
    restart: unless-stopped
    depends_on:
      - db
  db:
      image: mongo:4.4.3
      volumes:
        - /home/phimlau/mongodb/database:/data/db
      restart: unless-stopped